import Foundation

let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let source = root.appending(path: "Sources/SwitcherCore/Resources/LanguageDetector/v2-word-ranks.tsv")
let corpusSource = root.appending(path: "Resources/LanguageDetector/source/v2-corpus.tsv")
let corpusOutput = root.appending(path: "Sources/SwitcherCore/Generated/LanguageDetectorCorpusV2.swift")

let rows = try String(contentsOf: source, encoding: .utf8)
    .split(whereSeparator: \.isNewline)
    .filter { !$0.hasPrefix("#") && !$0.isEmpty }
    .map { line -> (word: String, rank: Int) in
        let fields = line.split(separator: "\t", omittingEmptySubsequences: false)
        guard fields.count == 3, let rank = Int(fields[1]), rank > 0 else {
            fatalError("Invalid detector source row: \(line)")
        }
        return (String(fields[2]).precomposedStringWithCanonicalMapping.lowercased(), rank)
    }

guard Set(rows.map(\.word)).count == rows.count else { fatalError("Detector source contains duplicate words") }

let corpusRows = try String(contentsOf: corpusSource, encoding: .utf8)
    .split(whereSeparator: \.isNewline)
    .filter { !$0.hasPrefix("#") && !$0.isEmpty }
    .map { line -> (category: String, word: String, candidate: String) in
        let fields = line.split(separator: "\t", omittingEmptySubsequences: false)
        guard fields.count == 3, ["mustCorrect", "mustKeep", "ambiguous"].contains(String(fields[0])) else {
            fatalError("Invalid detector corpus row: \(line)")
        }
        return (String(fields[0]), String(fields[1]), String(fields[2]))
    }
let corpusEntries = corpusRows.map {
    "        .init(category: .\($0.category), word: \"\($0.word)\", candidate: \"\($0.candidate)\")"
}.joined(separator: ",\n")
let generatedCorpus = """
// Generated by Scripts/prepare-language-resources.swift from Resources/LanguageDetector/source/v2-corpus.tsv.

public enum LanguageDetectorCorpusCategory: Sendable, Equatable {
    case mustCorrect
    case mustKeep
    case ambiguous
}

public struct LanguageDetectorCorpusEntry: Sendable {
    public let category: LanguageDetectorCorpusCategory
    public let word: String
    public let candidate: String
}

public enum LanguageDetectorCorpus {
    public static let version = \"2\"
    public static let entries: [LanguageDetectorCorpusEntry] = [
\(corpusEntries)
    ]
}
"""
try generatedCorpus.write(to: corpusOutput, atomically: true, encoding: .utf8)
